# Generated by Django 3.1.4 on 2020-12-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofeedback',
            name='feedback',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='audiofeedback',
            name='name',
            field=models.CharField(default='', max_length=264),
        ),
    ]
